# This file contains values from Cookiecutter

default_context:
  project_name: "librus-restx"
  project_description: "Librus Synergia Rest Api."
  organization: "librus-restx"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "librus_restx"
  email: "whinitc2@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
